### ISSUE TITLE
Bug - Error 404 on working RTSP source

### ISSUE THREAD

**Issue by Chambana** [aler9/mediamtx#1608]
## Which version are you using?

v0.21.6

## Which operating system are you using?

- [X] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description Please closed issue https://github.com/aler9/rtsp-simple-server/issues/1607 which Github keeps closing

## Describe how to replicate the issue

1. start the server
2. publish with ...
3. read with ...

## Did you attach the server logs?

yes

## Did you attach a network dump?

yes

**Comment by aler9** [comment]
replied in #1607
