### ISSUE TITLE
Possible bug - confname comes through as regex

### ISSUE THREAD

**Issue by jolbol1** [aler9/mediamtx#1649]
## Which version are you using?

v0.22.0

## Which operating system are you using?

- [x] Linux amd64 Docker

## Describe the issue

When adding a stream, the API reports the confName as `~^.*$`, the regex for any string. 

When calling `/v1/paths/list` I get:
```json
    "items": {
        "test": {
            "confName": "~^.*$",
            "conf": ...
```
When calling `/v1/config/get` I get:
```JSON
    "paths": {
        "~^.*$": {...}
```

I am unsure if this is intended behaviour, I seem to remeber confName just equalling the path name at one point. If this is intended could I get an explanation on how the name is selected?

If its not intended but to minor to look at I can have a go at fixing it.

The regex string appears to come from this block of code: https://github.com/aler9/mediamtx/blob/053f2ec282e464cb65a29b4ae69710a107de4429/internal/conf/conf.go#L454-L462

## Describe how to replicate the issue

1. start the server, turning on the HTTP API
2. publish 2 streams with ffmpeg
```bash
ffmpeg -re -f lavfi -i "testsrc=size=1280x720:rate=30" -c:v libx264 -preset ultrafast -tune zerolatency -b:v 500k -maxrate 500k -bufsize 1000k -framerate 30 -g 60 -pix_fmt yuv420p -f rtsp rtsp://localhost:8554/test -f rtsp rtsp://localhost:8554/test1
```
3. call the api using `/v1/config/get` and `/v1/paths/list`
4. See behaviour reported above

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by aler9** [comment]
Hello, the server implements two different entities: paths and path configurations. The entries you write in the configuration file are path configurations. Path configurations are associated to zero or more paths through regexps.

When you publish a stream to a path, the server finds the path configuration associated to that path. In the default configuration file, there's only one path configuration, the "all" one. Therefore, publishing to path "/test" means using path configuration "all". Which is the one correctly reported as `confName` in the API. If you want a different confName or a different configuration for path "test", define a path configuration called "test" in the configuration file.
