### ISSUE TITLE
rpiCamera saturation parameter

### ISSUE THREAD

**Issue by FantomeP** [aler9/mediamtx#1651]
## Which version are you using?

v0.22.0

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [x] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue
I have an issue with implementation of https://github.com/aler9/mediamtx/issues/1111 with my rpiCamera NoIR. 
I want to set the colors in a grey scale, since i don't want a blue-pink world. The saturation parameter with libcamera sets colors to a greyscale when set to 0, as specified in https://www.raspberrypi.com/documentation/computers/camera_software.html#libcamera-vid : 
---------------
	--saturation			Set image colour saturation <number>
The given <number> adjusts the colour saturation. The value zero produces a greyscale image, the value 1.0 uses the default amount of sautration, and values greater than 1.0 apply extra colour saturation.
---------------

Description

## Describe how to replicate the issue
Setting the saturation to 0 in mediamtx.yml parameter or launching docker run with MTX...._SATURATION=0 doesn't set the colors to greyscale mode. It looks like the saturation is in a default value 1.

1. start the server
2. publish with ... docker and my own parameters of mediamtx.yml or in docker run parameters
3. read with ... vlc or frigate on homeassistant with ffmpeg

## Did you attach the server logs?

no

## Did you attach a network dump?

no

**Comment by DrJPK** [comment]
I have the same issue on arm64 standard.  I can't tell if it is a saturation issue or an AWB problem. I have set rpiCameraAWB to greyworld which is accepted fine by the yaml parser but I cannot seem to get rid of the pink.

Does anyone know which file actually reads these yaml settings and processes them for the piOS system? I'm not familiar with go, but am happy to have a look and play to see if I can work out where the problem really is.  Just need a hint as to where to start

**Comment by aler9** [comment]
Hello, this is caused by the fact that the server interprets the "zero" value as the default value, and replaces it with the default value, which in case of saturation is 1.
This behavior will be changed.

**Comment by FantomeP** [comment]
> I have the same issue on arm64 standard. I can't tell if it is a saturation issue or an AWB problem. I have set rpiCameraAWB to greyworld which is accepted fine by the yaml parser but I cannot seem to get rid of the pink.
> 
> Does anyone know which file actually reads these yaml settings and processes them for the piOS system? I'm not familiar with go, but am happy to have a look and play to see if I can work out where the problem really is. Just need a hint as to where to start

Greyworld has been implemented in AWB for raspivid, but not in Libcamera-vid. I've tried the config.txt parameter awb_auto_is_greyworld=1 too, it seems limited to raspivid too.

**Comment by Tormund1985** [comment]
Same problem with IMX477 and 462, pink video.

**Comment by FantomeP** [comment]
Hello,
I pulled the 0.22.2, i tried both giving the parameter in the run command and in the mediamtx.yml file, it seems like i still can't get my saturation to 0. Is anyone else still having the problem ?

**Comment by aler9** [comment]
fixed in v0.23.0
