### ISSUE TITLE
Authentication seem impossible using OBS 64bit RTMP

### ISSUE THREAD

**Issue by Shakesbeard** [aler9/mediamtx#1670]
## Which version are you using?

v0.22.0

## Which operating system are you using?

- [x] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Description

## Describe how to replicate the issue

I am trying to set up basic internal authentication by username and password for use with OBS v29.0.2 64bit.
I am using the default configuration file which is shipped with the release package.
I modify the publishUser and publishPass setting. I have tried providing the credentials for the config file with and without quotes as well in the combinations raw and sha256.

1. start the server without any commandline options, just using the minialistic modified config file
2. publish with OBS using RTMP custom server and authentication enabled, providing the credentials
This results with this message on server side:
INF [RTMP] [conn ....] closed (invalid credentials)

## Did you attach the server logs?

no
The log does not produce anything useful in addition on debug mode in regards to this issue.

## Did you attach a network dump?

no

## Verdict
I think there might be something specific to how OBS is handling the handshake. Unfortunately I cannot create a network dump :(
Unfortunately, OBS does not accept URL encoded username and password. This breaks the server hostname resolution in OBS.

However, the issue should be super easy to reproduce for you.
As a workaround, would it be possible to provide authentication for OBS by other means? Like url query parameters or based on the streamkey field?

**Comment by aler9** [comment]
Hello, as clearly stated in the README, credentials from OBS must be passed through query parameters:

> If credentials are in use, use the following parameters:
> 
>     Service: Custom...
>     Server: rtmp://localhost
>     Stream key: mystream?user=myuser&pass=mypass
