### ISSUE TITLE
support for gstreamer hlsink

### ISSUE THREAD

**Issue by wbtcpip2** [aler9/mediamtx#1693]
## Describe the feature
add support for gstreamer hlsink

Description
as you know gstreamer hlsink will store playlist.m3u8 and segmentsxxx.ts in a local path.
it would be nice if mediamtx can serve those files through is hls server

**Comment by aler9** [comment]
Hello, the content of a folder is not enough to generate a modern HLS stream, in particular:

* the server must put on hold requests to some playlist (blocking playlists) and unlock them as soon as the playlist is ready, and this implies knowing in advance when and how the playlist is generated
* in case of low-latency, parts are generated and written to a playlist multiple times per second. Speed of disk I/O can't keep up with this process, therefore parts have to be kept in RAM
* control over playlist and segment content is lost and there's no certainty of generating a valid stream

This is one of the reasons why GStreamer and FFmpeg are not able to generate low-latency HLS streams and are stick to an old HLS version. Just use the server to generate the stream, and if you need the content of the segments, there's the `hlsDirectory` option.
