### ISSUE TITLE
Unifi RTSP streams cannot be proxied in v0.22.x

### ISSUE THREAD

**Issue by hanjo** [aler9/mediamtx#1702]
## Which version are you using?

v0.22.1

## Which operating system are you using?

- [ ] Linux amd64 standard
- [x] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ ] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

Hi,

I'm using the following configuration:
```
  cam1:
    source: rtsp://cam1.lokal/s0
    sourceProtocol: tcp
    sourceOnDemand: yes
    sourceOnDemandCloseAfter: 60s
```
This used to work perfectly fine on v0.21.6. After upgrading to v0.22.0 (or v0.22.1) VLC does not show video any more, although audio seems to work. This is true for all Unifi cameras that I have. Another brand works fine even with v0.22.x

I'm unsure how to start debugging this issue. The Log is a little bit different, but does not hint about any issues:

Log from v0.21.6 (working):
```
2023/04/13 20:49:04 INF [RTSP] [conn 192.168.1.2:61413] opened
2023/04/13 20:49:04 INF [RTSP] [session 22d595c0] created by 192.168.1.2:61413
2023/04/13 20:49:04 INF [RTSP] [session 22d595c0] is reading from path 'cam1', with TCP, 2 tracks (MPEG4-audio, H264)
2023/04/13 20:51:43 INF [RTSP] [session 22d595c0] destroyed (torn down by 192.168.1.2:61413)
2023/04/13 20:51:43 INF [RTSP] [conn 192.168.1.2:61413] closed (EOF)
```
Log from v0.22.1 (not working):
```
2023/04/13 20:48:37 INF [RTSP] [conn 192.168.1.2:61357] opened
2023/04/13 20:48:37 INF [path cam1] [rtsp source] started
2023/04/13 20:48:37 INF [path cam1] [rtsp source] ready: 2 tracks (MPEG4-audio-gen, H264)
2023/04/13 20:48:37 INF [RTSP] [session beac4b00] created by 192.168.1.2:61357
2023/04/13 20:48:37 INF [RTSP] [session beac4b00] is reading from path 'cam1', with TCP, 2 tracks (MPEG4-audio-gen, H264)
2023/04/13 20:49:04 INF [RTSP] [session beac4b00] destroyed (torn down by 192.168.1.2:61357)
2023/04/13 20:49:04 INF [RTSP] [conn 192.168.1.2:61357] closed (EOF)
2023/04/13 20:49:14 INF [path cam1] [rtsp source] stopped
```
Any ideas?

## Describe how to replicate the issue

1. start the server
2. use the configuration above with a Unifi camera (in my case G3 Flex and G5 Flex, but I suspect all Unifi cameras are affected)
3. access proxy rtsp url through VLC

## Did you attach the server logs?

yes

## Did you attach a network dump?

no

**Comment by hanjo** [comment]
Here is a network dump of the issue. 192.168.1.26 is the client (VLC), 172.18.1.78 is rtsp-simple-server and 192.168.250 is the video source (i.e. the camera feed). Decode port 7447 as RTSP.

This is for a different camera than mentioned above, but the issue is the same.

[rtsp.pcap.gz](https://github.com/aler9/mediamtx/files/11230246/rtsp.pcap.gz)

**Comment by aler9** [comment]
Hello, the dump you posted contains communication between the server and VLC, which seems corrupted.

Could you instead post communication between a camera and the server? it can be generated by using this configuration:

```yml
paths:
  cam:
    source: rtsp://camera-url
```

60 seconds are enough. Thank you.

**Comment by hanjo** [comment]
Hi,

both communications are in the same dump. Filter for the communication between 192.168.1.250:7447 and 172.18.1.78:44422 for the camera feed. It's only 15 seconds though, let me know if you need more.

This is the associated config:
```
  cam4:
    source: rtsp://protect.lokal:7447/KNHfC4zxAycSQyUi
    sourceProtocol: tcp
    sourceOnDemand: yes
    sourceOnDemandCloseAfter: 60s
```

**Comment by aler9** [comment]
@hanjo communication between camera and server is missing the RTSP handshake, it's not possible to decode the stream without it. Start recording the dump before starting the server.

**Comment by hanjo** [comment]
Ok, I shut down the server, started the capture, then started the server again. I then connected from the client (192.168.1.2) to rtsp-simple-server (172.18.1.78) using VLC, waited 30 seconds, then quit VLC, waited another 75 seconds and stopped the capture. I hope everything you need is in it now:

[rtsp8.pcap.gz](https://github.com/aler9/mediamtx/files/11236687/rtsp8.pcap.gz)

**Comment by aler9** [comment]
Thanks for providing data that allowed to replicate the issue. Please test this nightly release and let me know if it fixes the issue.

[mediamtx_v0.22.1-1-ge0dac36_darwin_amd64.tar.gz](https://github.com/aler9/mediamtx/files/11239102/mediamtx_v0.22.1-1-ge0dac36_darwin_amd64.tar.gz)
[mediamtx_v0.22.1-1-ge0dac36_linux_amd64.tar.gz](https://github.com/aler9/mediamtx/files/11239103/mediamtx_v0.22.1-1-ge0dac36_linux_amd64.tar.gz)
[mediamtx_v0.22.1-1-ge0dac36_linux_arm64v8.tar.gz](https://github.com/aler9/mediamtx/files/11239106/mediamtx_v0.22.1-1-ge0dac36_linux_arm64v8.tar.gz)
[mediamtx_v0.22.1-1-ge0dac36_linux_armv6.tar.gz](https://github.com/aler9/mediamtx/files/11239109/mediamtx_v0.22.1-1-ge0dac36_linux_armv6.tar.gz)
[mediamtx_v0.22.1-1-ge0dac36_linux_armv7.tar.gz](https://github.com/aler9/mediamtx/files/11239111/mediamtx_v0.22.1-1-ge0dac36_linux_armv7.tar.gz)
[mediamtx_v0.22.1-1-ge0dac36_windows_amd64.zip](https://github.com/aler9/mediamtx/files/11239112/mediamtx_v0.22.1-1-ge0dac36_windows_amd64.zip)

**Comment by hanjo** [comment]
Thanks for the quick fix! I can confirm the issue does not occur in the nightly. 👍

**Comment by aler9** [comment]
a new version (v0.22.2) has been released in order to propagate this urgent fix.
