### ISSUE TITLE
Publishing from OBS v29 HEVC fails

### ISSUE THREAD

**Issue by turkodamian2** [aler9/mediamtx#1796]
## Which version are you using?

v0.22.2

## Which operating system are you using?

- [ ] Linux amd64 standard
- [ ] Linux amd64 Docker
- [ ] Linux arm64 standard
- [ ] Linux arm64 Docker
- [ ] Linux arm7 standard
- [ ] Linux arm7 Docker
- [ ] Linux arm6 standard
- [ ] Linux arm6 Docker
- [ x] Windows amd64 standard
- [ ] Windows amd64 Docker (WSL backend)
- [ ] macOS amd64 standard
- [ ] macOS amd64 Docker
- [ ] Other (please describe)

## Describe the issue

I get an error when tring to Stream h265 video from OBS using the Nvidia NVENC HEVC encoder
2023/05/13 19:16:33 INF [RTMP] [conn 127.0.0.1:57770] closed (unsupported video codec: 0)
If I use the Nvidia Nvenc h.264 from OBS it works ok
Using OBS v29 on Windows 10 with RTX 3090 and latest mediamtx
Thanks

## Describe how to replicate the issue

1. start the server
2. publish with OBS v29 using Nvidia nven hevc encoder
3. OBS think it is streaming but on the mediamtx console i get error

## Did you attach the server logs?

2023/05/13 19:22:28 INF MediaMTX / rtsp-simple-server v0.22.2
2023/05/13 19:22:28 INF [RTSP] listener opened on :8554 (TCP), :8000 (UDP/RTP), :8001 (UDP/RTCP)
2023/05/13 19:22:28 INF [RTMP] listener opened on :1935
2023/05/13 19:22:28 INF [HLS] listener opened on :8888
2023/05/13 19:22:28 INF [WebRTC] listener opened on :8889 (HTTP)
2023/05/13 19:22:31 INF [RTMP] [conn 127.0.0.1:58302] opened
2023/05/13 19:22:31 INF [RTMP] [conn 127.0.0.1:58302] closed (unsupported video codec: 0)
2023/05/13 19:22:33 INF [RTMP] [conn 127.0.0.1:58303] opened
2023/05/13 19:22:34 INF [RTMP] [conn 127.0.0.1:58303] closed (unsupported video codec: 0)
2023/05/13 19:22:36 INF [RTMP] [conn 127.0.0.1:58304] opened
2023/05/13 19:22:36 INF [RTMP] [conn 127.0.0.1:58304] closed (unsupported video codec: 0)
2023/05/13 19:22:38 INF [RTMP] [conn 127.0.0.1:58305] opened
2023/05/13 19:22:39 INF [RTMP] [conn 127.0.0.1:58305] closed (unsupported video codec: 0)
2023/05/13 19:22:41 INF [RTMP] [conn 127.0.0.1:58376] opened
2023/05/13 19:22:41 INF [RTMP] [conn 127.0.0.1:58376] closed (unsupported video codec: 0)
2023/05/13 19:22:43 INF [RTMP] [conn 127.0.0.1:58380] opened
2023/05/13 19:22:44 INF [RTMP] [conn 127.0.0.1:58380] closed (unsupported video codec: 0)

## Did you attach a network dump?

no

**Comment by aler9** [comment]
This has already been solved by #1756. Just wait for the next release or compile the server from source.
